import MediaTierList from './MediaTierList'
import { useAnimeImages } from '../hooks/useAnimeImages'

const ANIME = [
  { id: 1,  name: 'Attack on Titan',                          image: '', years: '2013–2023', genres: ['Action', 'Drama'],       rating: 9.0, desc: 'In a world where humanity lives inside cities surrounded by enormous walls, a boy swears vengeance on Titans after they destroy his village.' },
  { id: 2,  name: 'Fullmetal Alchemist: Brotherhood',         image: '', years: '2009–2010', genres: ['Action', 'Fantasy'],     rating: 9.1, desc: 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their deceased mother goes terribly wrong.' },
  { id: 3,  name: 'Death Note',                               image: '', years: '2006–2007', genres: ['Thriller', 'Mystery'],   rating: 8.9, desc: 'A student discovers a supernatural notebook that allows him to kill anyone whose name is written in it.' },
  { id: 4,  name: 'Naruto',                                   image: '', years: '2002–2007', genres: ['Action', 'Adventure'],   rating: 8.3, desc: 'A young ninja dreams of becoming the greatest in his village, while carrying the burden of a sealed demon fox.' },
  { id: 5,  name: 'Demon Slayer',                             image: '', years: '2019–',     genres: ['Action', 'Fantasy'],     rating: 8.7, desc: 'After his family is slaughtered by demons, Tanjiro joins the Demon Slayer Corps to avenge them and cure his demonized sister.' },
  { id: 6,  name: 'Dragon Ball Z',                            image: '', years: '1989–1996', genres: ['Action', 'Sci-Fi'],      rating: 8.7, desc: 'Goku and friends defend Earth from increasingly powerful extraterrestrial villains in epic battles.' },
  { id: 7,  name: 'One Piece',                                image: '', years: '1999–',     genres: ['Action', 'Adventure'],   rating: 9.0, desc: 'Monkey D. Luffy sets out to find the ultimate treasure "One Piece" and become the Pirate King.' },
  { id: 8,  name: 'Hunter x Hunter',                         image: '', years: '2011–2014', genres: ['Action', 'Adventure'],   rating: 9.0, desc: 'A young boy follows in his father\'s footsteps to become a Hunter, a licensed professional who specializes in fantastic pursuits.' },
  { id: 9,  name: 'Jujutsu Kaisen',                           image: '', years: '2020–',     genres: ['Action', 'Horror'],      rating: 8.7, desc: 'A boy swallows a cursed talisman and becomes host to a powerful curse, forcing him to join a secret organization fighting curses.' },
  { id: 10, name: 'Vinland Saga',                             image: '', years: '2019–',     genres: ['Action', 'Historical'],  rating: 8.7, desc: 'Young Thorfinn grows up on a battlefield after his father\'s murder, pursuing revenge while witnessing the brutal world of Vikings.' },
  { id: 11, name: 'Cowboy Bebop',                             image: '', years: '1998–1999', genres: ['Sci-Fi', 'Action'],      rating: 8.9, desc: 'A ragtag group of bounty hunters chase criminals across the solar system in 2071, exploring themes of fate and regret.' },
  { id: 12, name: 'Steins;Gate',                              image: '', years: '2011–2012', genres: ['Sci-Fi', 'Thriller'],    rating: 9.1, desc: 'A self-proclaimed mad scientist accidentally discovers time travel and becomes entangled in a conspiracy with dire consequences.' },
  { id: 13, name: 'My Hero Academia',                         image: '', years: '2016–',     genres: ['Action', 'Superhero'],   rating: 8.4, desc: 'In a world where most people have superpowers, a boy born without any enters a prestigious hero school.' },
  { id: 14, name: 'Sword Art Online',                         image: '', years: '2012–',     genres: ['Sci-Fi', 'Action'],      rating: 7.6, desc: 'Players of a virtual reality MMORPG find themselves trapped inside when the game\'s creator holds them hostage.' },
  { id: 15, name: 'Re:Zero',                                  image: '', years: '2016–',     genres: ['Fantasy', 'Thriller'],   rating: 8.2, desc: 'A teenager is suddenly transported to a fantasy world and discovers he can reset time when he dies.' },
  { id: 16, name: 'Code Geass',                               image: '', years: '2006–2008', genres: ['Mecha', 'Drama'],        rating: 8.7, desc: 'An exiled prince uses a mysterious power to lead a rebellion against an empire that conquered Japan.' },
  { id: 17, name: 'Neon Genesis Evangelion',                  image: '', years: '1995–1996', genres: ['Mecha', 'Drama'],        rating: 8.6, desc: 'A teenager is recruited to pilot giant mechas against mysterious beings called Angels in a post-apocalyptic Tokyo.' },
  { id: 18, name: 'Bleach',                                   image: '', years: '2004–',     genres: ['Action', 'Fantasy'],     rating: 8.2, desc: 'A teenager gains the powers of a Soul Reaper and must protect the living world from malevolent spirits called Hollows.' },
  { id: 19, name: 'Chainsaw Man',                             image: '', years: '2022–',     genres: ['Action', 'Horror'],      rating: 8.7, desc: 'A poor young man merges with his dog-demon companion and becomes Chainsaw Man to hunt devils as a Public Safety Devil Hunter.' },
  { id: 20, name: 'Spy x Family',                             image: '', years: '2022–',     genres: ['Comedy', 'Action'],      rating: 8.6, desc: 'A spy must create a fake family to complete his mission, not knowing his fake daughter can read minds and his wife is an assassin.' },
  { id: 21, name: 'One Punch Man',                            image: '', years: '2015–',     genres: ['Action', 'Comedy'],      rating: 8.8, desc: 'A hero so powerful he can defeat any enemy with a single punch searches for a worthy opponent.' },
  { id: 22, name: 'Mob Psycho 100',                           image: '', years: '2016–',     genres: ['Action', 'Comedy'],      rating: 8.8, desc: 'A powerful psychic middle-schooler must not only deal with evil spirits but also navigate the difficulties of growing up.' },
  { id: 23, name: 'Violet Evergarden',                        image: '', years: '2018',       genres: ['Drama', 'Romance'],      rating: 8.7, desc: 'A former child soldier becomes an Auto Memory Doll, writing letters to help others express their feelings.' },
  { id: 24, name: 'Your Lie in April',                        image: '', years: '2014–2015', genres: ['Drama', 'Romance'],      rating: 8.6, desc: 'A piano prodigy who can no longer hear his music encounters a free-spirited violinist who changes his life.' },
  { id: 25, name: 'Parasyte: The Maxim',                      image: '', years: '2014–2015', genres: ['Sci-Fi', 'Horror'],      rating: 8.5, desc: 'A parasitic alien bonds with a boy\'s right hand instead of his brain, forcing them to cooperate to survive other aliens.' },
  { id: 26, name: 'No Game No Life',                          image: '', years: '2014',       genres: ['Fantasy', 'Comedy'],     rating: 8.2, desc: 'Sibling genius gamers are transported to a world where all conflicts are resolved through games.' },
  { id: 27, name: 'JoJo\'s Bizarre Adventure',               image: '', years: '2012–',     genres: ['Action', 'Supernatural'],rating: 8.8, desc: 'The multigenerational saga of the Joestar family, each member destined to battle the supernatural.' },
  { id: 28, name: 'Haikyuu!!',                                image: '', years: '2014–2020', genres: ['Sports', 'Comedy'],      rating: 8.7, desc: 'A boy determined to become a volleyball ace despite his short stature joins a high school team and strives to reach nationals.' },
  { id: 29, name: 'That Time I Got Reincarnated as a Slime',  image: '', years: '2018–',     genres: ['Fantasy', 'Adventure'],  rating: 8.1, desc: 'An office worker is reincarnated as a powerful slime in a fantasy world, befriending monsters and building a nation.' },
  { id: 30, name: 'Mushoku Tensei',                           image: '', years: '2021–',     genres: ['Fantasy', 'Adventure'],  rating: 8.4, desc: 'A 34-year-old is reincarnated as Rudeus Greyrat in a magical world, vowing to live life without regrets.' },
  { id: 31, name: 'Toradora',                                 image: '', years: '2008–2009', genres: ['Romance', 'Comedy'],     rating: 8.2, desc: 'Two teens help each other with their love lives, gradually developing feelings for each other along the way.' },
  { id: 32, name: 'Overlord',                                 image: '', years: '2015–',     genres: ['Fantasy', 'Action'],     rating: 7.9, desc: 'When a popular game is shut down, a player\'s character is transported to a new world as his all-powerful avatar, Ainz Ooal Gown.' },
  { id: 33, name: 'Fairy Tail',                               image: '', years: '2009–2019', genres: ['Action', 'Fantasy'],     rating: 7.9, desc: 'A celestial wizard joins the most destructive magic guild in the kingdom, going on adventures with her newfound friends.' },
  { id: 34, name: 'Gintama',                                  image: '', years: '2006–2018', genres: ['Comedy', 'Action'],      rating: 8.9, desc: 'In Edo-period Japan invaded by aliens, a lazy samurai takes on odd jobs with his eccentric companions.' },
  { id: 35, name: 'Classroom of the Elite',                   image: '', years: '2017–',     genres: ['Thriller', 'Drama'],     rating: 7.8, desc: 'A quiet student discovers that his elite high school rewards merit with privileges while hiding dark secrets beneath.' },
  { id: 36, name: 'Oregairu (My Teen Romantic Comedy SNAFU)', image: '', years: '2013–2020', genres: ['Romance', 'Drama'],      rating: 8.4, desc: 'A cynical high schooler joins a club aimed at helping students with problems, leading to unexpected growth and connections.' },
  { id: 37, name: 'Fruits Basket',                            image: '', years: '2001–',     genres: ['Romance', 'Drama'],      rating: 8.3, desc: 'A girl discovers her classmates are cursed to transform into Chinese Zodiac animals, bringing her into their secretive lives.' },
  { id: 38, name: 'Black Clover',                             image: '', years: '2017–2021', genres: ['Action', 'Fantasy'],     rating: 8.0, desc: 'A boy born without magic aims to become the Wizard King in a world where magic is everything.' },
  { id: 39, name: 'Tokyo Ghoul',                              image: '', years: '2014–',     genres: ['Horror', 'Action'],      rating: 7.8, desc: 'A college student becomes a half-ghoul after a near-fatal encounter, forcing him to navigate both human and ghoul societies.' },
  { id: 40, name: 'Samurai Champloo',                         image: '', years: '2004–2005', genres: ['Action', 'Historical'],  rating: 8.5, desc: 'Two contrasting samurai and a girl form an uneasy alliance to search for a sunflower samurai in Edo Japan.' },
]

interface Props { onHome: () => void }

export default function AnimeTierList({ onHome }: Props) {
  const imageMap = useAnimeImages(ANIME)
  return <MediaTierList items={ANIME} imageMap={imageMap} onHome={onHome} shareFilename="anime-tierlist" />
}
