import MediaTierList from './MediaTierList'
import { useMovieImages } from '../hooks/useMovieImages'

const MOVIES = [
  { id: 1,  name: 'The Shawshank Redemption',              image: '', years: '1994', genres: ['Drama'],                     rating: 9.3, desc: 'A banker sentenced to life in Shawshank prison befriends a fellow prisoner and finds creative ways to keep his sanity.' },
  { id: 2,  name: 'The Godfather',                         image: '', years: '1972', genres: ['Crime', 'Drama'],            rating: 9.2, desc: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.' },
  { id: 3,  name: 'The Dark Knight',                       image: '', years: '2008', genres: ['Action', 'Crime'],           rating: 9.0, desc: 'Batman faces the Joker, a criminal mastermind who wants to plunge Gotham City into anarchy.' },
  { id: 4,  name: 'Pulp Fiction',                          image: '', years: '1994', genres: ['Crime', 'Drama'],            rating: 8.9, desc: 'The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence and redemption.' },
  { id: 5,  name: "Schindler's List",                      image: '', years: '1993', genres: ['Drama', 'History'],          rating: 9.0, desc: 'In German-occupied Poland during WWII, industrialist Oskar Schindler saves more than a thousand Jewish refugees.' },
  { id: 6,  name: 'The Lord of the Rings: The Fellowship of the Ring', image: '', years: '2001', genres: ['Fantasy', 'Adventure'], rating: 8.8, desc: 'A meek Hobbit sets out to destroy an ancient ring that threatens to dominate all life in Middle Earth.' },
  { id: 7,  name: 'Forrest Gump',                          image: '', years: '1994', genres: ['Drama', 'Comedy'],           rating: 8.8, desc: 'The life journey of a kind-hearted man from Alabama who influences several historical events in the 20th century.' },
  { id: 8,  name: 'Inception',                             image: '', years: '2010', genres: ['Sci-Fi', 'Thriller'],        rating: 8.8, desc: "A thief who enters people's dreams to steal secrets is offered a chance to have his criminal record erased." },
  { id: 9,  name: 'The Matrix',                            image: '', years: '1999', genres: ['Sci-Fi', 'Action'],          rating: 8.7, desc: 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.' },
  { id: 10, name: 'Goodfellas',                            image: '', years: '1990', genres: ['Crime', 'Drama'],            rating: 8.7, desc: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his partners.' },
  { id: 11, name: 'Fight Club',                            image: '', years: '1999', genres: ['Drama', 'Thriller'],         rating: 8.8, desc: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club.' },
  { id: 12, name: 'Interstellar',                          image: '', years: '2014', genres: ['Sci-Fi', 'Drama'],           rating: 8.7, desc: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival." },
  { id: 13, name: 'The Silence of the Lambs',              image: '', years: '1991', genres: ['Horror', 'Thriller'],        rating: 8.6, desc: 'A young FBI cadet must confide in an incarcerated and manipulative killer to catch another serial killer.' },
  { id: 14, name: 'Parasite',                              image: '', years: '2019', genres: ['Thriller', 'Drama'],         rating: 8.5, desc: 'Greed and class discrimination threaten the symbiotic relationship between the wealthy Park family and the destitute Kim clan.' },
  { id: 15, name: 'Avengers: Endgame',                     image: '', years: '2019', genres: ['Action', 'Sci-Fi'],          rating: 8.4, desc: 'After half of all life is wiped out by Thanos, the Avengers assemble once more to undo his actions.' },
  { id: 16, name: 'Joker',                                 image: '', years: '2019', genres: ['Drama', 'Thriller'],         rating: 8.4, desc: 'A failed stand-up comedian spirals into madness, becoming the iconic villain of Gotham City.' },
  { id: 17, name: 'The Lion King',                         image: '', years: '1994', genres: ['Animation', 'Drama'],        rating: 8.5, desc: 'A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility.' },
  { id: 18, name: 'Toy Story',                             image: '', years: '1995', genres: ['Animation', 'Comedy'],       rating: 8.3, desc: 'A cowboy doll is threatened when a new spaceman toy becomes the most popular toy.' },
  { id: 19, name: 'Gladiator',                             image: '', years: '2000', genres: ['Action', 'Drama'],           rating: 8.5, desc: 'A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family.' },
  { id: 20, name: 'The Departed',                          image: '', years: '2006', genres: ['Crime', 'Thriller'],         rating: 8.5, desc: 'An undercover cop and a mole in the police attempt to identify each other while working for a criminal organization.' },
  { id: 21, name: 'Whiplash',                              image: '', years: '2014', genres: ['Drama', 'Music'],            rating: 8.5, desc: 'A promising young drummer enrolls at a cutthroat music conservatory where his relationship with an abusive instructor pushes him to his limits.' },
  { id: 22, name: 'Mad Max: Fury Road',                    image: '', years: '2015', genres: ['Action', 'Sci-Fi'],          rating: 8.1, desc: 'In a post-apocalyptic wasteland, Max teams with a mysterious woman to flee from a warlord.' },
  { id: 23, name: 'The Grand Budapest Hotel',              image: '', years: '2014', genres: ['Comedy', 'Drama'],           rating: 8.1, desc: 'A writer encounters the owner of an aging European hotel and hears of his experiences in the 1930s.' },
  { id: 24, name: 'La La Land',                            image: '', years: '2016', genres: ['Romance', 'Musical'],        rating: 8.0, desc: 'A jazz musician and an aspiring actress fall in love while chasing their dreams in Los Angeles.' },
  { id: 25, name: 'Get Out',                               image: '', years: '2017', genres: ['Horror', 'Thriller'],        rating: 7.7, desc: "A Black man visits his white girlfriend's parents for the weekend, where increasingly disturbing discoveries unfold." },
  { id: 26, name: 'Dune',                                  image: '', years: '2021', genres: ['Sci-Fi', 'Adventure'],       rating: 8.0, desc: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset." },
  { id: 27, name: 'Everything Everywhere All at Once',     image: '', years: '2022', genres: ['Sci-Fi', 'Action'],          rating: 7.8, desc: 'A middle-aged Chinese immigrant is swept up in an insane adventure where she alone can save the world.' },
  { id: 28, name: 'Oppenheimer',                           image: '', years: '2023', genres: ['Drama', 'History'],          rating: 8.3, desc: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.' },
  { id: 29, name: 'Top Gun: Maverick',                     image: '', years: '2022', genres: ['Action', 'Drama'],           rating: 8.3, desc: 'After 30 years, Maverick is back as a top instructor pushing a group of graduates for a special mission.' },
  { id: 30, name: 'Spider-Man: Into the Spider-Verse',     image: '', years: '2018', genres: ['Animation', 'Action'],       rating: 8.4, desc: 'Teen Miles Morales becomes the Spider-Man of his reality and must team up with his counterparts from other dimensions.' },
  { id: 31, name: 'Knives Out',                            image: '', years: '2019', genres: ['Mystery', 'Comedy'],         rating: 7.9, desc: 'A detective investigates the death of a crime novelist at his estate, uncovering family secrets.' },
  { id: 32, name: '1917',                                  image: '', years: '2019', genres: ['War', 'Drama'],              rating: 8.2, desc: 'Two British soldiers are sent on a mission to deliver a message that will stop 1,600 of their men from walking into a trap.' },
  { id: 33, name: 'Blade Runner 2049',                     image: '', years: '2017', genres: ['Sci-Fi', 'Drama'],           rating: 8.0, desc: "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard." },
  { id: 34, name: 'The Revenant',                          image: '', years: '2015', genres: ['Drama', 'Adventure'],        rating: 8.0, desc: 'A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.' },
  { id: 35, name: 'Gone Girl',                             image: '', years: '2014', genres: ['Thriller', 'Drama'],         rating: 8.1, desc: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him." },
  { id: 36, name: 'No Country for Old Men',                image: '', years: '2007', genres: ['Crime', 'Thriller'],         rating: 8.2, desc: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and some money.' },
  { id: 37, name: 'The Social Network',                    image: '', years: '2010', genres: ['Drama', 'Biography'],        rating: 7.7, desc: 'As Harvard student Mark Zuckerberg creates Facebook, he is sued by the twins who claimed he stole their idea.' },
  { id: 38, name: 'Eternal Sunshine of the Spotless Mind', image: '', years: '2004', genres: ['Romance', 'Sci-Fi'],         rating: 8.3, desc: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.' },
  { id: 39, name: 'Saving Private Ryan',                   image: '', years: '1998', genres: ['War', 'Drama'],              rating: 8.6, desc: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed.' },
  { id: 40, name: 'The Prestige',                          image: '', years: '2006', genres: ['Thriller', 'Mystery'],       rating: 8.5, desc: 'Two stage magicians engage in a competitive rivalry that leads to destructive consequences.' },
  { id: 41, name: 'Memento',                               image: '', years: '2000', genres: ['Mystery', 'Thriller'],       rating: 8.4, desc: "A man with short-term memory loss attempts to track down his wife's murderer." },
  { id: 42, name: 'City of God',                           image: '', years: '2002', genres: ['Crime', 'Drama'],            rating: 8.6, desc: "In the slums of Rio de Janeiro in the 1970s, two kids' paths diverge — one becomes a photographer, the other a drug dealer." },
  { id: 43, name: 'The Truman Show',                       image: '', years: '1998', genres: ['Drama', 'Sci-Fi'],           rating: 8.1, desc: 'An insurance salesman discovers his entire life is a reality TV show.' },
  { id: 44, name: 'Amélie',                                image: '', years: '2001', genres: ['Romance', 'Comedy'],         rating: 8.3, desc: 'Amélie decides to improve the lives of those around her while searching for love herself.' },
  { id: 45, name: 'Spirited Away',                         image: '', years: '2001', genres: ['Animation', 'Fantasy'],      rating: 8.6, desc: 'A 10-year-old girl wanders into a world ruled by gods, spirits, and monsters.' },
  { id: 46, name: 'Princess Mononoke',                     image: '', years: '1997', genres: ['Animation', 'Fantasy'],      rating: 8.4, desc: 'On a journey to find the cure for a curse, Ashitaka encounters a young woman who fights to protect the forest from humanity.' },
  { id: 47, name: 'A Beautiful Mind',                      image: '', years: '2001', genres: ['Drama', 'Biography'],        rating: 8.2, desc: 'After math prodigy John Nash begins to develop paranoid schizophrenia, he recovers and wins the Nobel Prize.' },
  { id: 48, name: '12 Angry Men',                          image: '', years: '1957', genres: ['Drama'],                     rating: 9.0, desc: 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.' },
  { id: 49, name: 'Oldboy',                                image: '', years: '2003', genres: ['Thriller', 'Mystery'],       rating: 8.4, desc: 'After being kidnapped and imprisoned for fifteen years, a man is released and given five days to find his captor.' },
  { id: 50, name: 'Hereditary',                            image: '', years: '2018', genres: ['Horror', 'Drama'],           rating: 7.3, desc: 'A grieving family is haunted by their ancestry as their mother passes and releases a dark presence in their lives.' },
]

interface Props { onHome: () => void }

export default function MovieTierList({ onHome }: Props) {
  const imageMap = useMovieImages(MOVIES)
  return <MediaTierList items={MOVIES} imageMap={imageMap} onHome={onHome} shareFilename="movie-tierlist" />
}
